export const ADD_TOPPING = 'ADD_TOPPING';
export const REMOVE_TOPPING = 'REMOVE_TOPPING';
export const SET_TOPPINGS = 'SET_TOPPINGS';
export const INIT_TOPPINGS = 'INIT_TOPPINGS';
export const FETCH_TOPPING_ERROR = 'FETCH_TOPPING_ERROR';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_CANCEL = 'PURCHASE_CANCEL';